### ISSUE TITLE
Why a standalone version of Lark and not Lark as a dependency?

### ISSUE THREAD

**Issue by eduardo-rodrigues** [scikit-hep/formulate#52]
I noticed that you are presently using an old-ish version when several new releases, including the 1.2 series, came out in the meantime. What is the reason for not having Lark as a strict dependency and profit automatically from improvements and bug fixes?

Ping @aryan26roy and @jonas-eschle.

**Comment by aryan26roy** [comment]
@eduardo-rodrigues I have been developing this library on and off for over the last year (basically whenever I find the time outside of my job). Back when we started, v1.1.7 was the latest release for Lark and it never crossed my mind to upgrade it.

The reason we have a standalone version of Lark instead of having it as a dependency has to do with Uproot. Or at least that is one of the reasons. @jpivarski wanted it to be as light of a dependency as possible so that it can be integrated into Uproot easily. 

As for improvements and bug fixes, can we not periodically generate the standalone scripts to fix any major issues with the parser, if and when we discover them in the future?

I am also wondering whether we will really benefit from future releases apart from critical bug fixes, given we are not using an ambiguous grammar.

**Comment by eduardo-rodrigues** [comment]
I thought these things but better to have them spelled out. Yes, that makes sense and in this instance that seems the best approach. Yes, you can in a follow-up PR update Lark. That's a good idea at this point, towards a major new release, I would say.

Thank you for the speedy reply.
